### ISSUE TITLE
确定项目名称

### ISSUE THREAD

**Issue by Hugo1030** [Hugo1030/Private-library#1]
考虑到最终目的是做一个私人图书馆，具备全文检索功能，一种在线的spotlight。最小MVP是对开智学堂公众号的全文检索，看看大家对项目名称有什么好的想法？

我先来抛砖引玉：
* 「开搜(open search)」-- 开始搜索，同时搜索开智的意思

**Comment by wuhuhu800** [comment]
项目名称：独家记忆，我觉得是：独家有一种个体所有权的感觉，同时“记忆”又隐隐含着人的大脑的延伸，和一首流行歌名同名，便于记忆。

**Comment by elevenera** [comment]
来一起头脑风暴了，不成熟的小建议：
- 思书－－谐音私塾、撕书；思：思念、思考；思念书籍、思考知识

**Comment by Hugo1030** [comment]
最后确定项目名称--记忆宫殿(mind palace)
