### ISSUE TITLE
为团队取个响应的名称吧！还有个人介绍

### ISSUE THREAD

**Issue by Hugo1030** [Hugo1030/Private-library#2]
- 团队名称：为你的团队取个响应的名称吧！
- 团队成员：介绍每位团队成员和分工
   - 成员 A （名号 - GitHub Username - 所在城市）
       - 140 字以内的个人简介（主要分工、特长等）
   - 成员 B （名号 - GitHub Username - 所在城市）
       - 140 字以内的个人简介

**Comment by wuhuhu800** [comment]
成员 武虎（阿虎-wuhuhu800-北京）
原去哪儿网产品经理，现在辞职1个月，全力学习python中。过程中可以从产品的角度带着大家一起做好这个MVP。希望在这里和大家一起成长，相互启迪。

**Comment by Hugo1030** [comment]
团队名称：黑骑士(Black Knight)

**Comment by elevenera** [comment]
成员 刘纪元（eleven－elevenera－北京）
原去哪儿网PMO，现离职状态，学习python，希望成为创造者。项目过程中可以参与需求、技术开发、测试等环节，与团队协作一起努力完成好这个作品。
