### ISSUE TITLE
整理需求需要回答的几个问题

### ISSUE THREAD

**Issue by wuhuhu800** [Hugo1030/Private-library#4]
以下内容是我本周分享的部分，先提前放到这里，大家想一想：
#### 用户是谁：（最终产出物：用户画像）
- 哪类人会用到我们的产品？
- 这些人有什么特点？
- 这些人没有我们的产品之前是怎么管理自己的微信公众号和图书的，有什么痛点？
- 用了我们的产品是否能解决这个这个痛点，为什么？
以上四点问题，前两点很重要，因为之后的设计上思考点都基于我的用户是谁这一基础之上。

#### 用户做什么：（最终产出物：带有优先级的功能的列表）
- 用户为什么来我们这里？（解决痛点的功能）
- 用户来我们这里需要不得不做些什么？（注册、登录等）
- 用户来我们这里还能够做哪些？（除了痛点，其他的功能）
当然有时间的话大家可以看一下对于需求分类[***KANO模型***](https://www.zhihu.com/question/22989667)

#### 用户怎么做：（最终产物：页面流程图-是页面设计材料主要输入）
- 根据上面的功能列表，梳理每一个功能点使用场景，也就是用户在什么情况下会用到这个功能。

关于需求这部分我个人建议大家在9月20日之前，形成初步意见，我汇总，然后大家再修订。

页面设计的部分（后续我再发issue）

**Comment by Hugo1030** [comment]
### 用户是谁：（最终产出物：用户画像）
#### 哪类人会用到我们的产品？
- 知识创造者，不只是每天消费很多信息，而且会再次使用这些信息的人。

#### 这些人有什么特点？
- 每天网上阅读大量信息，并且需要迅速调取这些信息。

#### 这些人没有我们的产品之前是怎么管理自己的微信公众号和图书的，有什么痛点？
- 读了那么多书，可是却想不起来喜欢的故事出现在哪本书的哪个章节？
- 看了那么多微信公众号文章，可是某个片段却再也找不回来？

#### 用了我们的产品是否能解决这个这个痛点，为什么？
- 使用我们的产品，用户不必记忆太多的信息，只需要有一点印象，便可以检索到相关信息，这样相当于把自己的记忆外部化到我们产品上了。

### 用户做什么：（最终产出物：带有优先级的功能的列表）

#### 用户为什么来我们这里？
- 我们不止搜集信息，更是帮助用户高效检索信息。
- 指定微信公众号的检索，更加准确高效获取信息。
- 自动爬取感兴趣的报刊杂志，并支持全文检索。

#### 用户来我们这里需要不得不做些什么？
- 注册、登陆

#### 用户来我们这里还能够做哪些？（除了痛点，其他的功能）
- 定期获取已订阅杂志的信息，并支持全文检索。

#### 用户怎么做：（最终产物：页面流程图-是页面设计材料主要输入）
- 登陆或注册（该页面显示本产品的功能及基本介绍）
- 全文检索页面 （显示已添加书籍或已关注的公众微信号）
- 上传书籍页面 （上传功能+用户手动为书籍命名）
- 添加公众号页面 （我已添加的公众号+添加新的公众号+热门公众号推荐）
