### ISSUE TITLE
20170923 Week0Day6_项目及团队名称&项目梳理&任务分工

### ISSUE THREAD

**Issue by Hugo1030** [Hugo1030/Private-library#6]
## 20170923 Week0Day6_项目及团队名称&项目梳理&任务分工
* 参会人：沥川、阿虎、刘纪元、容与
* 地点：zoom

## Abstract

* 确定项目及团队名称
* 任务细节梳理
* 协作方式及任务分工

## Info
* 确定项目名称-记忆宫殿(Mind Palace)
* 确定团队名称-黑骑士(Black Knight)
* 每周碰面两次，周三线下聚会，周日上午9:42 ZOOM线上聚会，线下聚会录音。
* 每人轮流写备忘录，第一次由沥川完成。
* 前期按照各自兴趣，领取自己喜欢任务，共同协作完成。后期分配任务，每人完成各自功能模块，拼接完成。大家完成的模块上传到develop分支上，沥川负责汇总。
* 可以考虑使用Bootstrap完成页面制作。
* 微信爬虫功能分解
    * 爬取微信公众号历史信息
    * 添加公众号
    * 定时自动爬取
    * 将爬取信息按特定格式保存入数据库
* 全文检索功能分解
    * 调用API或者相关库，完成全文关键词匹配功能
    * 完成匹配结果高亮显示功能
    * 完成查询结果展示功能
* 页面制作功能分解
    * 用户注册功能页面
    * 用户登陆功能页面
    * 用户添加、删除公众号页面（包含推荐公众号）
    * 用户查询匹配检索页面
    * 项目介绍页面
* 网站的部署
    * MVP使用heroku快速部署上线
    * 测试成功后考虑部署到阿里云等国内云平台

## Action
* 10月1日前，请阿虎完成产品流程图，并和容与沟通页面细节。
* 10月1日前，请沥川、阿虎、纪元协作完成爬取微信历史信息功能。
* 请容与完成页面制作功能。
* 请纪元、容与完成个人介绍。
* 请沥川完成第一次聚会备忘录。

## Question

无

## Changelog
170923 沥川创建

**Comment by linfeng365** [comment]
+1
