### ISSUE TITLE
记忆宫殿-功能梳理及原型设计

### ISSUE THREAD

**Issue by wuhuhu800** [Hugo1030/Private-library#7]
以下是我对记忆宫殿的功能梳理，大家看一下，有什么需要调整或者补充的，以及有什么不理解的可以回复一下。要是看不清楚的话，可以下载文件[记忆宫殿梳理.xmind.zip](https://github.com/Hugo1030/Private-library/files/1333462/xmind.zip)看，用Xmid软件打开。
争取后天（28号）下午前给我反馈，这周争取把网站的原型图给画出来。

<img width="536" alt="wx20170926-220151 2x" src="https://user-images.githubusercontent.com/21167490/30864703-f8310390-a306-11e7-9a12-5986e503fa08.png">
<img width="1100" alt="wx20170926-220249 2x" src="https://user-images.githubusercontent.com/21167490/30864710-fdd41288-a306-11e7-86e9-f45a55f68ceb.png">
<img width="1610" alt="wx20170926-220351 2x" src="https://user-images.githubusercontent.com/21167490/30864705-f8c25f84-a306-11e7-9233-414b6d7020ff.png">
<img width="471" alt="wx20170926-220415 2x" src="https://user-images.githubusercontent.com/21167490/30864707-faf5d9de-a306-11e7-9229-f6e48bf639bf.png">
<img width="1501" alt="wx20170926-220537 2x" src="https://user-images.githubusercontent.com/21167490/30864712-ffa89bd8-a306-11e7-9020-56dad405919d.png">

**Comment by wuhuhu800** [comment]
页面流程图：大家看一下有什么问题，到时候一起讨论一下
<img width="1424" alt="wx20170930-161012 2x" src="https://user-images.githubusercontent.com/21167490/31044116-a7cf13da-a58e-11e7-9005-31b897181e16.png">

**Comment by wuhuhu800** [comment]
原型图：画了主要页面的低保真原型图，有些小内容，目前没有做，例如：弹窗原型，发邮箱的文案等。原型图的原文件可以用浏览器打开，点击[原型图axure.zip](https://github.com/Hugo1030/Private-library/files/1346254/axure.zip)下载。
把主要页面放出来，这样方便大家看一下：
**首页**
<img width="1114" alt="wx20170930-161155 2x" src="https://user-images.githubusercontent.com/21167490/31044148-94e8b266-a58f-11e7-8fea-25e54c90d4f2.png">
**公众号页面**
<img width="1366" alt="wx20170930-161714 2x" src="https://user-images.githubusercontent.com/21167490/31044157-ab49c3a6-a58f-11e7-9cf9-f8a0084019c4.png">
**个人空间页面**
_个人公众号部分_
<img width="1366" alt="- wx20170930-161752 2x" src="https://user-images.githubusercontent.com/21167490/31044162-bf8f6668-a58f-11e7-8028-965a410a4b09.png">
_搜索结果部分_
<img width="1127" alt="- wx20170930-161825 2x" src="https://user-images.githubusercontent.com/21167490/31044167-d7dae698-a58f-11e7-956f-534a00172b21.png">
**全文详情页**
<img width="1365" alt="wx20170930-161901 2x" src="https://user-images.githubusercontent.com/21167490/31044173-e7bc4a02-a58f-11e7-838f-bac50a225705.png">
**注册页面**
<img width="1073" alt="wx20170930-162019 2x" src="https://user-images.githubusercontent.com/21167490/31044178-fda3ee56-a58f-11e7-8db4-4cec5a76e160.png">
**登录页面**
<img width="1078" alt="wx20170930-162043 2x" src="https://user-images.githubusercontent.com/21167490/31044182-0e549cb4-a590-11e7-9fa6-0d6de5fabfb5.png">
**找回密码页**
<img width="1050" alt="wx20170930-162111 2x" src="https://user-images.githubusercontent.com/21167490/31044185-1e1b1baa-a590-11e7-9e5d-9d86eef7d63d.png">

**Comment by momo-o** [comment]
感谢虎哥！有了这个思路，我做网页清晰很多。
下面两点我还有点不清楚，想确认一下。
1. 整体搜索方式：
	- 单次搜索：需要搜索时，即时添加公众号。添加完进行关键词搜索，可进行多次搜索，一旦重置（退出），添加的公众号记录不再保存。
	- 个人账号式搜索：把公众号添入账号，需要搜索的时候再从这些公众号中进行选择，可以再添公众号时增加标签，用时可以按标签搜索。（感觉要保留用户的话应该是这种方式比较好，看下来我们的思路也是基于这种搜索方式？不知道我是否有没get到的功能点。）
2. 公众号页面的功能。
	- 是做“陌生”公众号搜索用，还是同时做已添加的公众号搜索。
	- 如果是“陌生”公众号搜索，刚进入该页面，没有输入搜索内容时，也就是下面没有公众号列表时，是否需要另做一个纯搜索页面。
3. 个人页面。
        -是否在勾选完想要的公众号之后，添一个本次搜索勾选的公众号的列表。或者是否有其他方式向用户确认一下这次搜索的搜索范围。

**Comment by wuhuhu800** [comment]
##### 1、整体搜索
- 单次搜索：我理解的是在公众号里进行搜索，只是把已有的公众号通过关键词进行检索出来。重置的意思是将搜索框里的值清空，同时已有的将公众号列表全部显示，也就是刚进入公众号时的默认状态的样子。
- 个人账号式搜索：我的理解是将公众号添加到个人空间之后，在个人空间搜索的时候，是基于个人空间里的公众号，对这些公众号的文章内容进行全文的检索。我理解你说的标签功能是指，对个人空间里的公众号进行打标签，可以通过标签检索出公众号？
##### 2、公众号页面的功能
- 这版原型是基于已经添加的公众号进行搜索，如果要是以后可以做陌生公众号的搜索，脑洞一下，我觉得到时候可以直接在把陌生公众号搜索放到个人空间里，这样用操作更方便，就不必在公众号页面和个人空间页面来回切换。而公众号页面就只是做一些公众号推荐类的了，要是想有收入的话，这部分是可以做点文章的，哈哈后话了。
##### 3、个人页面
- 思羽，你提到的这想法太棒了，目前这版设计的检索范围的灵活程度还是非常有限的，范围只能局限在全部书籍类（当然本次应该不太会做上传书籍功能）、全部公众号、或者某一个公众号。而没有设计成更加灵活的自定义某几个公众号。我在回复你的时候已经开始认真考虑怎么设计自定义的问题了，但突然想到，这样做可能时间不是很够，下次开会的时候，我们可以讨论一下这项功能。

**Comment by mydream378** [comment]
@wuhuhu800 虎哥，你们的项目好赞呀，请问，你的页面流程图和思维导图是什么app制作的呢？

**Comment by wuhuhu800** [comment]
经过进一步的务实，MVP简化为如下，大家看一下，提一下意见：
页面流程图：
<img width="947" alt="wx20171015-232251- 2x" src="https://user-images.githubusercontent.com/21167490/31586194-965c9e86-b193-11e7-84ce-c9791c046ea4.png">
首页图：
<img width="1019" alt="wx20171015-232414- 2x" src="https://user-images.githubusercontent.com/21167490/31586203-a3505006-b193-11e7-931a-52f03725ba33.png">
老阳搜-未搜索状态
<img width="958" alt="wx20171015-232451 -1 2x" src="https://user-images.githubusercontent.com/21167490/31586223-d3f807c6-b193-11e7-8316-6ebbe39b5afd.png">

老阳搜-搜索状态
<img width="1122" alt="wx20171015-232525 -2 2x" src="https://user-images.githubusercontent.com/21167490/31586226-dc595208-b193-11e7-9861-2bdc62fb6ea3.png">

全文详情页
<img width="1048" alt="wx20171015-232551 2x" src="https://user-images.githubusercontent.com/21167490/31586231-e47e7918-b193-11e7-889a-d91a4f4e9c05.png">
